# Generated by Django 5.1.3 on 2024-12-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
